/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(account-creation)/account-recovery': RouteRecordInfo<
      '/(account-creation)/account-recovery',
      '/account-recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(account-creation)/creation': RouteRecordInfo<
      '/(account-creation)/creation',
      '/creation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(account-creation)/get-started': RouteRecordInfo<
      '/(account-creation)/get-started',
      '/get-started',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-panel': RouteRecordInfo<
      'admin-panel',
      '/admin/admin-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'tickets': RouteRecordInfo<
      'tickets',
      '/admin/tickets',
      Record<never, never>,
      Record<never, never>,
      | '/admin/tickets/'
      | '/admin/tickets/archived'
    >,
    '/admin/tickets/': RouteRecordInfo<
      '/admin/tickets/',
      '/admin/tickets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tickets/archived': RouteRecordInfo<
      '/admin/tickets/archived',
      '/admin/tickets/archived',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/announcements': RouteRecordInfo<
      '/admin/announcements',
      '/admin/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/demands': RouteRecordInfo<
      '/admin/demands',
      '/admin/demands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/emails': RouteRecordInfo<
      '/admin/emails',
      '/admin/emails',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/pending-users': RouteRecordInfo<
      '/admin/pending-users',
      '/admin/pending-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rules': RouteRecordInfo<
      '/admin/rules',
      '/admin/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar': RouteRecordInfo<
      '/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/center/[centerId]/teams': RouteRecordInfo<
      '/center/[centerId]/teams',
      '/center/:centerId/teams',
      { centerId: ParamValue<true> },
      { centerId: ParamValue<false> },
      | never
    >,
    '/center/centers': RouteRecordInfo<
      '/center/centers',
      '/center/centers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact-admin': RouteRecordInfo<
      '/contact-admin',
      '/contact-admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demand-page': RouteRecordInfo<
      '/demand-page',
      '/demand-page',
      Record<never, never>,
      Record<never, never>,
      | '/demand-page/demands'
      | '/demand-page/demands/'
      | '/demand-page/standalone'
      | '/demand-page/standalone/available'
      | '/demand-page/standalone/own'
    >,
    '/demand-page/demands': RouteRecordInfo<
      '/demand-page/demands',
      '/demand-page/demands',
      Record<never, never>,
      Record<never, never>,
      | '/demand-page/demands/'
    >,
    '/demand-page/demands/': RouteRecordInfo<
      '/demand-page/demands/',
      '/demand-page/demands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demand-page/standalone': RouteRecordInfo<
      '/demand-page/standalone',
      '/demand-page/standalone',
      Record<never, never>,
      Record<never, never>,
      | '/demand-page/standalone/available'
      | '/demand-page/standalone/own'
    >,
    '/demand-page/standalone/available': RouteRecordInfo<
      '/demand-page/standalone/available',
      '/demand-page/standalone/available',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demand-page/standalone/own': RouteRecordInfo<
      '/demand-page/standalone/own',
      '/demand-page/standalone/own',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/financement': RouteRecordInfo<
      '/financement',
      '/financement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/haptic': RouteRecordInfo<
      '/haptic',
      '/haptic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/landing': RouteRecordInfo<
      '/landing',
      '/landing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/loading': RouteRecordInfo<
      '/loading',
      '/loading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/messages': RouteRecordInfo<
      '/messages',
      '/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patchnotes': RouteRecordInfo<
      '/patchnotes',
      '/patchnotes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pending-approval': RouteRecordInfo<
      '/pending-approval',
      '/pending-approval',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/[userId]': RouteRecordInfo<
      '/profile/[userId]',
      '/profile/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/profile/[userId].change-history': RouteRecordInfo<
      '/profile/[userId].change-history',
      '/profile/:userId/change-history',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/profile/[userId].transaction-history': RouteRecordInfo<
      '/profile/[userId].transaction-history',
      '/profile/:userId/transaction-history',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rotation': RouteRecordInfo<
      '/rotation',
      '/rotation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-graph': RouteRecordInfo<
      '/test-graph',
      '/test-graph',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-params': RouteRecordInfo<
      '/user-params',
      '/user-params',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users': RouteRecordInfo<
      '/users',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(account-creation)/account-recovery.vue': {
      routes:
        | '/(account-creation)/account-recovery'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(account-creation)/creation.vue': {
      routes:
        | '/(account-creation)/creation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(account-creation)/get-started.vue': {
      routes:
        | '/(account-creation)/get-started'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/admin-panel.vue': {
      routes:
        | 'admin-panel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/tickets.vue': {
      routes:
        | '/admin/tickets/'
        | '/admin/tickets/archived'
        | 'tickets'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/admin/tickets/index.vue': {
      routes:
        | '/admin/tickets/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/tickets/archived.vue': {
      routes:
        | '/admin/tickets/archived'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/announcements.vue': {
      routes:
        | '/admin/announcements'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/demands.vue': {
      routes:
        | '/admin/demands'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/emails.vue': {
      routes:
        | '/admin/emails'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/pending-users.vue': {
      routes:
        | '/admin/pending-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/rules.vue': {
      routes:
        | '/admin/rules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/calendar.vue': {
      routes:
        | '/calendar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/center/[centerId]/teams.vue': {
      routes:
        | '/center/[centerId]/teams'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/center/centers.vue': {
      routes:
        | '/center/centers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/contact-admin.vue': {
      routes:
        | '/contact-admin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/demand-page.vue': {
      routes:
        | '/demand-page'
        | '/demand-page/demands'
        | '/demand-page/demands/'
        | '/demand-page/standalone'
        | '/demand-page/standalone/available'
        | '/demand-page/standalone/own'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/demand-page/demands.vue': {
      routes:
        | '/demand-page/demands'
        | '/demand-page/demands/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/demand-page/demands/index.vue': {
      routes:
        | '/demand-page/demands/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/demand-page/standalone.vue': {
      routes:
        | '/demand-page/standalone'
        | '/demand-page/standalone/available'
        | '/demand-page/standalone/own'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/demand-page/standalone/available.vue': {
      routes:
        | '/demand-page/standalone/available'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/demand-page/standalone/own.vue': {
      routes:
        | '/demand-page/standalone/own'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/financement.vue': {
      routes:
        | '/financement'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/haptic.vue': {
      routes:
        | '/haptic'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/landing.vue': {
      routes:
        | '/landing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/loading.vue': {
      routes:
        | '/loading'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/messages.vue': {
      routes:
        | '/messages'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/patchnotes.vue': {
      routes:
        | '/patchnotes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pending-approval.vue': {
      routes:
        | '/pending-approval'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/[userId].vue': {
      routes:
        | '/profile/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/profile/[userId].change-history.vue': {
      routes:
        | '/profile/[userId].change-history'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/profile/[userId].transaction-history.vue': {
      routes:
        | '/profile/[userId].transaction-history'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/rotation.vue': {
      routes:
        | '/rotation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/test-graph.vue': {
      routes:
        | '/test-graph'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user-params.vue': {
      routes:
        | '/user-params'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users.vue': {
      routes:
        | '/users'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
