/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/(account-creation)/account-recovery': RouteRecordInfo<'/(account-creation)/account-recovery', '/account-recovery', Record<never, never>, Record<never, never>>,
    '/(account-creation)/creation': RouteRecordInfo<'/(account-creation)/creation', '/creation', Record<never, never>, Record<never, never>>,
    '/(account-creation)/get-started': RouteRecordInfo<'/(account-creation)/get-started', '/get-started', Record<never, never>, Record<never, never>>,
    '/admin/account-recovery': RouteRecordInfo<'/admin/account-recovery', '/admin/account-recovery', Record<never, never>, Record<never, never>>,
    '/admin/admin-panel': RouteRecordInfo<'/admin/admin-panel', '/admin/admin-panel', Record<never, never>, Record<never, never>>,
    '/admin/pending-users': RouteRecordInfo<'/admin/pending-users', '/admin/pending-users', Record<never, never>, Record<never, never>>,
    '/admin/rules': RouteRecordInfo<'/admin/rules', '/admin/rules', Record<never, never>, Record<never, never>>,
    '/admin/tickets': RouteRecordInfo<'/admin/tickets', '/admin/tickets', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/center/[centerId]/teams': RouteRecordInfo<'/center/[centerId]/teams', '/center/:centerId/teams', { centerId: ParamValue<true> }, { centerId: ParamValue<false> }>,
    '/center/centers': RouteRecordInfo<'/center/centers', '/center/centers', Record<never, never>, Record<never, never>>,
    '/contact-admin': RouteRecordInfo<'/contact-admin', '/contact-admin', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/emails': RouteRecordInfo<'/emails', '/emails', Record<never, never>, Record<never, never>>,
    '/exchange/replace': RouteRecordInfo<'/exchange/replace', '/exchange/replace', Record<never, never>, Record<never, never>>,
    '/exchange/switch': RouteRecordInfo<'/exchange/switch', '/exchange/switch', Record<never, never>, Record<never, never>>,
    '/financement': RouteRecordInfo<'/financement', '/financement', Record<never, never>, Record<never, never>>,
    '/haptic': RouteRecordInfo<'/haptic', '/haptic', Record<never, never>, Record<never, never>>,
    '/landing': RouteRecordInfo<'/landing', '/landing', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/messages': RouteRecordInfo<'/messages', '/messages', Record<never, never>, Record<never, never>>,
    '/parameter': RouteRecordInfo<'/parameter', '/parameter', Record<never, never>, Record<never, never>>,
    '/patchnotes': RouteRecordInfo<'/patchnotes', '/patchnotes', Record<never, never>, Record<never, never>>,
    '/pending-approval': RouteRecordInfo<'/pending-approval', '/pending-approval', Record<never, never>, Record<never, never>>,
    '/profile/[userId]': RouteRecordInfo<'/profile/[userId]', '/profile/:userId', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
    '/profile/[userId].change-history': RouteRecordInfo<'/profile/[userId].change-history', '/profile/:userId/change-history', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
    '/profile/[userId].transaction-history': RouteRecordInfo<'/profile/[userId].transaction-history', '/profile/:userId/transaction-history', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/rotation': RouteRecordInfo<'/rotation', '/rotation', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
